{
  "swagger" : "2.0",
  "info" : {
    "version" : "2023-10-16T16:22:13Z",
    "title" : "product-service-dev"
  },
  "host" : "wpwd3ayme3.execute-api.eu-west-1.amazonaws.com",
  "basePath" : "/dev",
  "schemes" : [ "https" ],
  "paths" : {
    "/hello" : {
      "post" : {
        "consumes" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "producApiGaaHkobBN6Nziq",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/producApiGaaHkobBN6Nziq"
          }
        } ],
        "responses" : { }
      },
      "options" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "responses" : {
          "200" : {
            "description" : "200 response",
            "headers" : {
              "Access-Control-Allow-Origin" : {
                "type" : "string"
              },
              "Access-Control-Allow-Methods" : {
                "type" : "string"
              },
              "Access-Control-Allow-Headers" : {
                "type" : "string"
              }
            }
          }
        }
      }
    },
    "/product" : {
      "get" : {
        "responses" : { }
      },
      "post" : {
        "consumes" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "producApiGaJS4TTJMNXu7O",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/producApiGaJS4TTJMNXu7O"
          }
        } ],
        "responses" : { }
      },
      "options" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "responses" : {
          "200" : {
            "description" : "200 response",
            "headers" : {
              "Access-Control-Allow-Origin" : {
                "type" : "string"
              },
              "Access-Control-Allow-Methods" : {
                "type" : "string"
              },
              "Access-Control-Allow-Headers" : {
                "type" : "string"
              }
            }
          }
        }
      }
    },
    "/product/{id}" : {
      "get" : {
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : { }
      },
      "options" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "200 response",
            "headers" : {
              "Access-Control-Allow-Origin" : {
                "type" : "string"
              },
              "Access-Control-Allow-Methods" : {
                "type" : "string"
              },
              "Access-Control-Allow-Headers" : {
                "type" : "string"
              }
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "producApiGaJS4TTJMNXu7O" : {
      "type" : "object",
      "required" : [ "products" ],
      "properties" : {
        "products" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "properties" : {
              "price" : {
                "type" : "number"
              },
              "count" : {
                "type" : "number"
              },
              "description" : {
                "type" : "string"
              },
              "id" : {
                "type" : "string"
              },
              "title" : {
                "type" : "string"
              }
            }
          }
        }
      }
    },
    "producApiGaaHkobBN6Nziq" : {
      "type" : "object",
      "required" : [ "name" ],
      "properties" : {
        "name" : {
          "type" : "string"
        }
      }
    }
  }
}